<query> ::= <expression> <eof>
<expression> ::= <and> | <or> | <not> | <must> | <must_not> | <boost> | <fuzzy> | <literal>
<and> ::= <expression> "AND" <expression>
<or> ::= <expression> "OR" <expression>
<not> ::= "NOT" <expression>
<must> ::= "+" <literal>
<must_not> ::= "-" <literal>
<boost> ::= <expression> "^" <number> | <expression> "^"
<fuzzy> ::= <expression> "~" <number> | <expression> "~"
<literal> ::= "[a-zA-Z0-9]" | <wildcard> | <regexp>
