name: Bump Release

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup go
              uses: actions/setup-go@v3
              with:
                  go-version: 'stable'

            - name: test
              run: go test -v ./...

            - name: fuzz test
              run: go test -v ./fuzz

            - uses: grindlemire/bump-release-action@master
              with:
                  config_path: '.github/bump.yml'
