name: Create Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v3

            - name: setup go
              uses: actions/setup-go@v3
              with:
                  go-version: 'stable'

            - name: set tagname
              id: tag
              run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

            - name: set major version name
              id: major_version
              run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3 | cut -d . -f 1)" >> $GITHUB_OUTPUT

            - name: test
              run: go test -v ./...

            - name: fuzz test
              run: go test -v ./fuzz

            - name: release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ steps.tag.outputs.version }}

            - name: create release branch
              uses: peterjgrainger/action-create-branch@v2.2.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  branch: release-branch.${{ steps.major_version.outputs.version }}

            - name: merge to release branch
              uses: tukasz/direct-merge-action@v2.0.2
              with:
                  source-branch: main
                  target-branch: release-branch.${{ steps.major_version.outputs.version }}
                  commit-message: Automatic merge from main for release ${{ steps.tag.outputs.version }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
